type: "simulstream.server.speech_processors.sliding_window_retranslation.HFSlidingWindowRetranslator"
hf_model_name: "FBK-MT/fama-small"
window_len: 12
supported_langs:
  - en
  - it
lang_tag_template: "<lang:{}>"
matching_threshold: 0.1