hostname: localhost
port: 8080
secure: false
model_name: FAMA
model_logo: FAMA.png
supported_langs:
  - en: "ðŸ‡¬ðŸ‡§ English"
  - it: "ðŸ‡®ðŸ‡¹ Italian"
speech_processing_frequency: 2.0  # seconds

metrics:
  enabled: True
  filename: "metrics.jsonl"
